version: "3"
services:
  root:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: root
    working_dir: '/root'
    tty: true
    volumes: 
      - ./root:/root
    ports: 
      - '8501:8501'
    # command: streamlit run app.py